# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

from google.protobuf import empty_pb2 as google_dot_protobuf_dot_empty__pb2
import library_pb2 as library__pb2

GRPC_GENERATED_VERSION = '1.63.0'
GRPC_VERSION = grpc.__version__
EXPECTED_ERROR_RELEASE = '1.65.0'
SCHEDULED_RELEASE_DATE = 'June 25, 2024'
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    warnings.warn(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + f' but the generated code in library_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
        + f' This warning will become an error in {EXPECTED_ERROR_RELEASE},'
        + f' scheduled for release on {SCHEDULED_RELEASE_DATE}.',
        RuntimeWarning
    )


class LibraryServiceStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.CreateAuthor = channel.unary_unary(
                '/liberary.LibraryService/CreateAuthor',
                request_serializer=library__pb2.AuthorRequest.SerializeToString,
                response_deserializer=library__pb2.AuthorResponse.FromString,
                _registered_method=True)
        self.CreateBook = channel.unary_unary(
                '/liberary.LibraryService/CreateBook',
                request_serializer=library__pb2.BookRequest.SerializeToString,
                response_deserializer=library__pb2.BookResponse.FromString,
                _registered_method=True)
        self.CreateBookCopy = channel.unary_unary(
                '/liberary.LibraryService/CreateBookCopy',
                request_serializer=library__pb2.BookCopyRequest.SerializeToString,
                response_deserializer=library__pb2.BookCopyResponse.FromString,
                _registered_method=True)
        self.CreateMember = channel.unary_unary(
                '/liberary.LibraryService/CreateMember',
                request_serializer=library__pb2.MemberRequest.SerializeToString,
                response_deserializer=library__pb2.MemberResponse.FromString,
                _registered_method=True)
        self.BorrowCopy = channel.unary_unary(
                '/liberary.LibraryService/BorrowCopy',
                request_serializer=library__pb2.BorrowRequest.SerializeToString,
                response_deserializer=library__pb2.BorrowResponse.FromString,
                _registered_method=True)
        self.ListBooks = channel.unary_unary(
                '/liberary.LibraryService/ListBooks',
                request_serializer=google_dot_protobuf_dot_empty__pb2.Empty.SerializeToString,
                response_deserializer=library__pb2.BookListResponse.FromString,
                _registered_method=True)
        self.GetBook = channel.unary_unary(
                '/liberary.LibraryService/GetBook',
                request_serializer=library__pb2.BookRecord.SerializeToString,
                response_deserializer=library__pb2.BookResponse.FromString,
                _registered_method=True)


class LibraryServiceServicer(object):
    """Missing associated documentation comment in .proto file."""

    def CreateAuthor(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def CreateBook(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def CreateBookCopy(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def CreateMember(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def BorrowCopy(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ListBooks(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetBook(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_LibraryServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'CreateAuthor': grpc.unary_unary_rpc_method_handler(
                    servicer.CreateAuthor,
                    request_deserializer=library__pb2.AuthorRequest.FromString,
                    response_serializer=library__pb2.AuthorResponse.SerializeToString,
            ),
            'CreateBook': grpc.unary_unary_rpc_method_handler(
                    servicer.CreateBook,
                    request_deserializer=library__pb2.BookRequest.FromString,
                    response_serializer=library__pb2.BookResponse.SerializeToString,
            ),
            'CreateBookCopy': grpc.unary_unary_rpc_method_handler(
                    servicer.CreateBookCopy,
                    request_deserializer=library__pb2.BookCopyRequest.FromString,
                    response_serializer=library__pb2.BookCopyResponse.SerializeToString,
            ),
            'CreateMember': grpc.unary_unary_rpc_method_handler(
                    servicer.CreateMember,
                    request_deserializer=library__pb2.MemberRequest.FromString,
                    response_serializer=library__pb2.MemberResponse.SerializeToString,
            ),
            'BorrowCopy': grpc.unary_unary_rpc_method_handler(
                    servicer.BorrowCopy,
                    request_deserializer=library__pb2.BorrowRequest.FromString,
                    response_serializer=library__pb2.BorrowResponse.SerializeToString,
            ),
            'ListBooks': grpc.unary_unary_rpc_method_handler(
                    servicer.ListBooks,
                    request_deserializer=google_dot_protobuf_dot_empty__pb2.Empty.FromString,
                    response_serializer=library__pb2.BookListResponse.SerializeToString,
            ),
            'GetBook': grpc.unary_unary_rpc_method_handler(
                    servicer.GetBook,
                    request_deserializer=library__pb2.BookRecord.FromString,
                    response_serializer=library__pb2.BookResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'liberary.LibraryService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class LibraryService(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def CreateAuthor(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/liberary.LibraryService/CreateAuthor',
            library__pb2.AuthorRequest.SerializeToString,
            library__pb2.AuthorResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def CreateBook(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/liberary.LibraryService/CreateBook',
            library__pb2.BookRequest.SerializeToString,
            library__pb2.BookResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def CreateBookCopy(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/liberary.LibraryService/CreateBookCopy',
            library__pb2.BookCopyRequest.SerializeToString,
            library__pb2.BookCopyResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def CreateMember(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/liberary.LibraryService/CreateMember',
            library__pb2.MemberRequest.SerializeToString,
            library__pb2.MemberResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def BorrowCopy(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/liberary.LibraryService/BorrowCopy',
            library__pb2.BorrowRequest.SerializeToString,
            library__pb2.BorrowResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ListBooks(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/liberary.LibraryService/ListBooks',
            google_dot_protobuf_dot_empty__pb2.Empty.SerializeToString,
            library__pb2.BookListResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetBook(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/liberary.LibraryService/GetBook',
            library__pb2.BookRecord.SerializeToString,
            library__pb2.BookResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
